name: bouldee
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  auto_route: ^9.2.2
  flutter_svg: ^2.0.16
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  supabase_flutter: ^2.8.4
  lucide_icons_flutter: ^1.2.7
  dotenv: ^4.2.0
  fl_chart: ^0.70.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  device_info_plus: ^11.3.3
  path: ^1.9.1
  connectivity_plus: ^6.1.3
  app_links: ^6.4.0


dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.7.0
  

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/logos/
    - assets/utils/

    - .env
