name: bouldee
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  auto_route: ^9.2.2
  flutter_svg: ^2.0.16
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  supabase_flutter: ^2.8.4


dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.7.0
  lucide_icons_flutter: ^1.2.7

flutter:
  uses-material-design: true
  generate: true
